const walmartBlue = "#0071CE";
const walmartBlueDark = "#005BA1";
const walmartYellow = "#FFC220";
const walmartYellowDark = "#E5AC00";

export default {
  light: {
    text: "#1A1A1A",
    textSecondary: "#444444",
    textTertiary: "#888888",
    background: "#F5F5F5",
    backgroundSecondary: "#FFFFFF",
    backgroundTertiary: "#E8E8E8",
    tint: walmartBlue,
    tintDark: walmartBlueDark,
    secondary: walmartYellow,
    secondaryDark: walmartYellowDark,
    tabIconDefault: "#888888",
    tabIconSelected: walmartBlue,
    border: "#E0E0E0",
    borderLight: "#EFEFEF",
    card: "#FFFFFF",
    overlay: "rgba(0, 0, 0, 0.5)",
    badge: walmartBlue,
    auctionBadge: "#E53935",
    buyNowBadge: walmartBlue,
    featuredBadge: walmartYellow,
    success: "#4CAF50",
    warning: "#FFC220",
    error: "#E53935",
    navy: "#1A1A1A",
  },
  dark: {
    text: "#F5F5F5",
    textSecondary: "#BBBBBB",
    textTertiary: "#888888",
    background: "#121212",
    backgroundSecondary: "#1E1E1E",
    backgroundTertiary: "#2A2A2A",
    tint: walmartBlue,
    tintDark: walmartBlueDark,
    secondary: walmartYellow,
    secondaryDark: walmartYellowDark,
    tabIconDefault: "#666666",
    tabIconSelected: walmartBlue,
    border: "#333333",
    borderLight: "#2A2A2A",
    card: "#1E1E1E",
    overlay: "rgba(0, 0, 0, 0.7)",
    badge: walmartBlue,
    auctionBadge: "#E53935",
    buyNowBadge: walmartBlue,
    featuredBadge: walmartYellow,
    success: "#4CAF50",
    warning: "#FFC220",
    error: "#E53935",
    navy: "#121212",
  },
};
