package crowdshipping

import (
	"fmt"
	"log/slog"
	"time"

	"github.com/geocore-next/backend/internal/config"
	"github.com/geocore-next/backend/internal/notifications"
	"github.com/geocore-next/backend/pkg/locking"
	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const (
	autoOfferConfidenceThreshold = 0.60
	maxAutoOffersPerRequest      = 3
	autoOfferExpiryHours         = 48
)

// GenerateAutoOffers creates auto-generated offers for high-confidence matches.
// Max 3 per request. Never overrides real user offers.
func GenerateAutoOffers(db *gorm.DB, notifSvc *notifications.Service, requestID uuid.UUID) error {
	if !config.GetFlags().EnableAutoOffers {
		slog.Info("auto_offer: skipped — feature flag disabled")
		return nil
	}

	matches, err := FindBestTravelersForRequest(db, requestID, 10)
	if err != nil {
		return fmt.Errorf("auto_offer: match failed: %w", err)
	}

	suggestion, _ := SuggestOfferPrice(db, requestID)

	created := 0
	for _, m := range matches {
		if created >= maxAutoOffersPerRequest {
			break
		}
		if !m.CanDeliver {
			continue
		}
		if m.Score < autoOfferConfidenceThreshold {
			break // sorted DESC, rest will be lower
		}

		err := locking.RetryOnDeadlock(db, func(tx *gorm.DB) error {
			// Re-check: no existing offer from this traveler
			var cnt int64
			tx.Model(&TravelerOffer{}).
				Where("delivery_request_id=? AND traveler_id=?", requestID, m.TravelerID).
				Count(&cnt)
			if cnt > 0 {
				return nil // skip, not an error
			}

			// Re-check: not already at max auto-offers
			var autoCnt int64
			tx.Model(&TravelerOffer{}).
				Where("delivery_request_id=? AND is_auto_generated=?", requestID, true).
				Count(&autoCnt)
			if autoCnt >= int64(maxAutoOffersPerRequest) {
				return nil
			}

			// Re-check: delivery request still available
			var dr DeliveryRequest
			if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).
				Where("id=? AND status IN ?", requestID,
					[]DeliveryStatus{DeliveryPending, DeliveryMatched, DeliveryAccepted}).
				First(&dr).Error; err != nil {
				return nil // no longer available
			}

			priceCents := suggestion.RecommendedCents
			if priceCents <= 0 {
				priceCents = toCents(dr.Reward)
			}
			price := fromCents(priceCents)
			platCents := priceCents * 15 / 100

			offer := TravelerOffer{
				DeliveryRequestID:     requestID,
				BuyerID:               dr.BuyerID,
				TravelerID:            m.TravelerID,
				PriceCents:            priceCents,
				Price:                 price,
				DeliveryFeeCents:      priceCents,
				DeliveryFee:           price,
				PlatformFeeCents:      platCents,
				TravelerEarningsCents: priceCents - platCents,
				Currency:              dr.Currency,
				Status:                OfferPending,
				PaymentRetryAllowed:   true,
				ExpiresAt:             time.Now().Add(autoOfferExpiryHours * time.Hour),
				IsAutoGenerated:       true,
				MatchScore:            m.Score,
				Note:                  "Auto-generated offer based on trip match",
			}
			if err := tx.Create(&offer).Error; err != nil {
				return err
			}
			created++
			return nil
		})
		if err != nil {
			slog.Error("auto_offer: create failed", "error", err)
		}
	}

	// Notify buyer about auto-offers
	if created > 0 && notifSvc != nil {
		var dr DeliveryRequest
		db.Where("id=?", requestID).First(&dr)
		go notifSvc.Notify(notifications.NotifyInput{
			UserID: dr.BuyerID, Type: "auto_offers_created",
			Title: "Auto-Matched Offers Ready!",
			Body:  fmt.Sprintf("%d travelers were auto-matched to your delivery request", created),
			Data:  map[string]string{"request_id": requestID.String(), "count": fmt.Sprintf("%d", created)},
		})
	}

	slog.Info("auto_offer: generated", "request_id", requestID, "created", created)
	return nil
}
