package crowdshipping

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type OfferStatus string

const (
	OfferPending        OfferStatus = "pending"
	OfferCountered      OfferStatus = "countered"
	OfferPaymentPending OfferStatus = "payment_pending"
	OfferFundsHeld      OfferStatus = "funds_held"
	OfferAccepted       OfferStatus = "accepted"
	OfferPaymentFailed  OfferStatus = "payment_failed"
	OfferRejected       OfferStatus = "rejected"
	OfferExpired        OfferStatus = "expired"
	OfferCompleted      OfferStatus = "completed"
	OfferCancelled      OfferStatus = "cancelled"
)

type TravelerOffer struct {
	ID                    uuid.UUID      `gorm:"type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	DeliveryRequestID     uuid.UUID      `gorm:"type:uuid;not null;index" json:"delivery_request_id"`
	BuyerID               uuid.UUID      `gorm:"type:uuid;not null;index" json:"buyer_id"`
	TravelerID            uuid.UUID      `gorm:"type:uuid;not null;index" json:"traveler_id"`
	PriceCents            int64          `gorm:"not null" json:"price_cents"`
	Price                 float64        `gorm:"type:decimal(15,2);not null" json:"price"`
	DeliveryFeeCents      int64          `gorm:"not null;default:0" json:"delivery_fee_cents"`
	DeliveryFee           float64        `gorm:"type:decimal(15,2);not null;default:0" json:"delivery_fee"`
	PlatformFeeCents      int64          `gorm:"not null;default:0" json:"platform_fee_cents"`
	TravelerEarningsCents int64          `gorm:"not null;default:0" json:"traveler_earnings_cents"`
	Currency              string         `gorm:"size:10;not null;default:'USD'" json:"currency"`
	Status                OfferStatus    `gorm:"size:30;not null;default:'pending';index" json:"status"`
	PaymentRetryAllowed   bool           `gorm:"not null;default:true" json:"payment_retry_allowed"`
	ExpiresAt             time.Time      `gorm:"not null" json:"expires_at"`
	Note                  string         `gorm:"type:text" json:"note,omitempty"`
	CounterToID           *uuid.UUID     `gorm:"type:uuid;index" json:"counter_to_id,omitempty"`
	OrderID               *uuid.UUID     `gorm:"type:uuid;index" json:"order_id,omitempty"`
	IdempotencyKey        string         `gorm:"size:64;index" json:"idempotency_key,omitempty"`
	IsAutoGenerated       bool           `gorm:"not null;default:false" json:"is_auto_generated"`
	MatchScore            float64        `gorm:"type:numeric(6,2);default:0" json:"match_score"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	DeletedAt             gorm.DeletedAt `gorm:"index" json:"-"`
}

func (TravelerOffer) TableName() string { return "traveler_offers" }

func (o *TravelerOffer) CanTransitionTo(target OfferStatus) bool {
	transitions := map[OfferStatus][]OfferStatus{
		OfferPending:        {OfferCountered, OfferPaymentPending, OfferRejected, OfferExpired, OfferCancelled},
		OfferCountered:      {OfferPending, OfferRejected, OfferExpired, OfferCancelled},
		OfferPaymentPending: {OfferFundsHeld, OfferPaymentFailed},
		OfferFundsHeld:      {OfferAccepted},
		OfferPaymentFailed:  {OfferPaymentPending},
		OfferAccepted:       {OfferCompleted, OfferCancelled},
	}
	allowed, ok := transitions[o.Status]
	if !ok {
		return false
	}
	for _, s := range allowed {
		if s == target {
			return true
		}
	}
	return false
}

func (o *TravelerOffer) IsActive() bool {
	return o.Status == OfferPending || o.Status == OfferCountered
}

// ── Shipment Tracking ────────────────────────────────────────────────────────

type ShipmentStatus string

const (
	ShipmentRequested      ShipmentStatus = "requested"
	ShipmentAccepted       ShipmentStatus = "accepted"
	ShipmentPurchased      ShipmentStatus = "purchased"
	ShipmentInTransit      ShipmentStatus = "in_transit"
	ShipmentArrivedCountry ShipmentStatus = "arrived_country"
	ShipmentOutForDelivery ShipmentStatus = "out_for_delivery"
	ShipmentDelivered      ShipmentStatus = "delivered"
	ShipmentConfirmed      ShipmentStatus = "confirmed"
	ShipmentCancelled      ShipmentStatus = "cancelled"
)

type TrackingEvent struct {
	ID            uuid.UUID      `gorm:"type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	OrderID       uuid.UUID      `gorm:"type:uuid;not null;index" json:"order_id"`
	TravelerID    uuid.UUID      `gorm:"type:uuid;not null;index" json:"traveler_id"`
	Status        ShipmentStatus `gorm:"size:30;not null;index" json:"status"`
	Location      string         `gorm:"size:255" json:"location,omitempty"`
	Note          string         `gorm:"type:text" json:"note,omitempty"`
	ProofImageURL string         `gorm:"type:text" json:"proof_image_url,omitempty"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (TrackingEvent) TableName() string { return "tracking_events" }

func NextAllowedStatuses(current ShipmentStatus) []ShipmentStatus {
	fsm := map[ShipmentStatus][]ShipmentStatus{
		ShipmentRequested:      {ShipmentAccepted, ShipmentCancelled},
		ShipmentAccepted:       {ShipmentPurchased},
		ShipmentPurchased:      {ShipmentInTransit},
		ShipmentInTransit:      {ShipmentArrivedCountry, ShipmentDelivered},
		ShipmentArrivedCountry: {ShipmentOutForDelivery, ShipmentDelivered},
		ShipmentOutForDelivery: {ShipmentDelivered},
		ShipmentDelivered:      {ShipmentConfirmed},
	}
	allowed, ok := fsm[current]
	if !ok {
		return nil
	}
	return allowed
}
