package crowdshipping

import (
	"testing"
	"time"

	"github.com/google/uuid"
)

// ── 1. MATCHING ACCURACY ────────────────────────────────────────────────────

func TestCountryScoreExact(t *testing.T) {
	trip := Trip{OriginCountry: "EG", DestCountry: "AE"}
	dr := DeliveryRequest{PickupCountry: "EG", DeliveryCountry: "AE"}
	if s := countryScore(trip, dr); s != 1.0 {
		t.Errorf("exact country match = %.2f, want 1.0", s)
	}
}

func TestCountryScorePartial(t *testing.T) {
	trip := Trip{OriginCountry: "EG", DestCountry: "SA"}
	dr := DeliveryRequest{PickupCountry: "EG", DeliveryCountry: "AE"}
	if s := countryScore(trip, dr); s != 0.5 {
		t.Errorf("partial country match = %.2f, want 0.5", s)
	}
}

func TestCountryScoreNoMatch(t *testing.T) {
	trip := Trip{OriginCountry: "US", DestCountry: "UK"}
	dr := DeliveryRequest{PickupCountry: "EG", DeliveryCountry: "AE"}
	if s := countryScore(trip, dr); s != 0 {
		t.Errorf("no country match = %.2f, want 0", s)
	}
}

func TestTimeScoreNoDeadline(t *testing.T) {
	trip := Trip{DepartureDate: time.Now().Add(24 * time.Hour)}
	dr := DeliveryRequest{}
	if s := timeScore(trip, dr); s != 1.0 {
		t.Errorf("no deadline = %.2f, want 1.0", s)
	}
}

func TestTimeScorePastDeadline(t *testing.T) {
	past := time.Now().Add(-1 * time.Hour)
	trip := Trip{DepartureDate: time.Now().Add(2 * time.Hour)}
	dr := DeliveryRequest{Deadline: &past}
	if s := timeScore(trip, dr); s != 0 {
		t.Errorf("past deadline = %.2f, want 0", s)
	}
}

func TestPriceScoreUnderBudget(t *testing.T) {
	w := 2.0
	trip := Trip{PricePerKg: 5.0, BasePrice: 3.0}
	dr := DeliveryRequest{Reward: 20.0, ItemWeight: &w}
	if s := priceScore(trip, dr); s != 1.0 {
		t.Errorf("under budget = %.2f, want 1.0", s)
	}
}

func TestPriceScoreOverBudget(t *testing.T) {
	w := 2.0
	trip := Trip{PricePerKg: 20.0, BasePrice: 10.0}
	dr := DeliveryRequest{Reward: 10.0, ItemWeight: &w}
	if s := priceScore(trip, dr); s != 0 {
		t.Errorf("way over budget = %.2f, want 0", s)
	}
}

// ── 2. SCORING CORRECTNESS ────────────────────────────────────────────────────

func TestScoringWeights(t *testing.T) {
	w := 2.0
	deadline := time.Now().Add(72 * time.Hour)
	trip := Trip{
		OriginCountry: "EG", DestCountry: "AE",
		OriginCity: "Cairo", DestCity: "Dubai",
		DepartureDate: time.Now().Add(12 * time.Hour),
		PricePerKg:    5.0, BasePrice: 3.0, AvailableWeight: 5.0,
	}
	dr := DeliveryRequest{
		PickupCountry: "EG", DeliveryCountry: "AE",
		PickupCity: "Cairo", DeliveryCity: "Dubai",
		Deadline: &deadline, Reward: 20.0, ItemWeight: &w,
	}

	cm := countryScore(trip, dr)
	tm := timeScore(trip, dr)
	pf := priceScore(trip, dr)
	rep := 80.0 // simulate

	score := cm*0.40 + tm*0.25 + (rep/100)*0.20 + pf*0.15

	if cm != 1.0 {
		t.Errorf("country = %.2f, want 1.0", cm)
	}
	if tm <= 0 {
		t.Errorf("time = %.2f, want > 0", tm)
	}
	if pf != 1.0 {
		t.Errorf("price = %.2f, want 1.0", pf)
	}
	if score < 0.60 {
		t.Errorf("total score = %.2f, want >= 0.60", score)
	}
}

func TestClamp(t *testing.T) {
	if clamp(-1, 0, 1) != 0 {
		t.Error("clamp(-1) should be 0")
	}
	if clamp(2, 0, 1) != 1 {
		t.Error("clamp(2) should be 1")
	}
	if clamp(0.5, 0, 1) != 0.5 {
		t.Error("clamp(0.5) should be 0.5")
	}
}

// ── 3. AUTO-OFFER LIMIT ────────────────────────────────────────────────────

func TestAutoOfferMaxLimit(t *testing.T) {
	if maxAutoOffersPerRequest != 3 {
		t.Errorf("max auto offers = %d, want 3", maxAutoOffersPerRequest)
	}
}

func TestAutoOfferConfidenceThreshold(t *testing.T) {
	if autoOfferConfidenceThreshold != 0.60 {
		t.Errorf("threshold = %.2f, want 0.60", autoOfferConfidenceThreshold)
	}
}

func TestAutoOfferExpiry(t *testing.T) {
	if autoOfferExpiryHours != 48 {
		t.Errorf("expiry = %d, want 48", autoOfferExpiryHours)
	}
}

// ── 4. NO DUPLICATE OFFERS ────────────────────────────────────────────────────

func TestAutoGeneratedOfferFields(t *testing.T) {
	o := TravelerOffer{
		IsAutoGenerated: true,
		MatchScore:      0.85,
		Status:          OfferPending,
	}
	if !o.IsAutoGenerated {
		t.Error("should be auto-generated")
	}
	if o.MatchScore != 0.85 {
		t.Errorf("match score = %.2f, want 0.85", o.MatchScore)
	}
	if !o.IsActive() {
		t.Error("auto-generated offer should be active (pending)")
	}
}

// ── 5. BROADCAST COOLDOWN ────────────────────────────────────────────────────

func TestBroadcastCooldown(t *testing.T) {
	if broadcastCooldownHours != 24 {
		t.Errorf("cooldown = %d, want 24", broadcastCooldownHours)
	}
}

// ── 6. SMART PRICING ────────────────────────────────────────────────────

func TestPriceSuggestionStructure(t *testing.T) {
	s := PriceSuggestion{
		MinCents:         700,
		RecommendedCents: 1000,
		MaxCents:         1300,
	}
	if s.MinCents >= s.RecommendedCents {
		t.Error("min should be < recommended")
	}
	if s.RecommendedCents >= s.MaxCents {
		t.Error("recommended should be < max")
	}
}

func TestFloatValNil(t *testing.T) {
	if v := floatVal(nil, 5.0); v != 5.0 {
		t.Errorf("nil = %.2f, want 5.0", v)
	}
}

func TestFloatValZero(t *testing.T) {
	z := 0.0
	if v := floatVal(&z, 5.0); v != 5.0 {
		t.Errorf("zero = %.2f, want 5.0", v)
	}
}

func TestFloatValPositive(t *testing.T) {
	v := 3.5
	if got := floatVal(&v, 5.0); got != 3.5 {
		t.Errorf("positive = %.2f, want 3.5", got)
	}
}

// ── 7. LIQUIDITY STATS ────────────────────────────────────────────────────

func TestLiquidityStatsDefaults(t *testing.T) {
	s := LiquidityStats{RequestID: uuid.New().String()}
	if s.OffersPerRequest != 0 {
		t.Error("default should be 0")
	}
	if s.AutoOfferAcceptRate != 0 {
		t.Error("default accept rate should be 0")
	}
}

// ── 8. BROADCAST LOG MODEL ────────────────────────────────────────────────────

func TestBroadcastLogTableName(t *testing.T) {
	bl := BroadcastLog{}
	if bl.TableName() != "broadcast_logs" {
		t.Errorf("table = %s, want broadcast_logs", bl.TableName())
	}
}

// ── 9. DEAL CLOSER TESTS ────────────────────────────────────────────────────

func TestPriceGapThreshold(t *testing.T) {
	if PriceGapThresholdCents != 500 {
		t.Errorf("threshold = %d, want 500", PriceGapThresholdCents)
	}
}

func TestMaxAutoClosePerUserPerDay(t *testing.T) {
	if MaxAutoClosePerUserPerDay != 5 {
		t.Errorf("daily limit = %d, want 5", MaxAutoClosePerUserPerDay)
	}
}

func TestDailyLimitCheck(t *testing.T) {
	// Reset state
	dailyAutoCloseCount = map[uuid.UUID]*int64{}
	dailyAutoCloseReset = time.Time{}

	uid := uuid.New()
	for i := 0; i < 5; i++ {
		if !checkDailyLimit(uid) {
			t.Errorf("iteration %d: should still be allowed", i+1)
		}
	}
	if checkDailyLimit(uid) {
		t.Error("6th auto-close should be blocked")
	}
}

func TestDailyLimitDifferentUsers(t *testing.T) {
	dailyAutoCloseCount = map[uuid.UUID]*int64{}
	dailyAutoCloseReset = time.Time{}

	u1 := uuid.New()
	u2 := uuid.New()
	if !checkDailyLimit(u1) || !checkDailyLimit(u2) {
		t.Error("different users should have independent limits")
	}
}

// ── 10. TRUST ENGINE TESTS ────────────────────────────────────────────────────

func TestComputeSellerScore(t *testing.T) {
	// Perfect seller
	s := ComputeSellerScore(5.0, 1.0, 0)
	if s < 90 {
		t.Errorf("perfect seller = %.1f, want >= 90", s)
	}
	// Bad seller
	s = ComputeSellerScore(1.0, 0.5, 0.3)
	if s > 50 {
		t.Errorf("bad seller = %.1f, want <= 50", s)
	}
}

func TestComputeTravelerScore(t *testing.T) {
	// Perfect traveler
	s := ComputeTravelerScore(1.0, 1.0, 5.0, 1.0)
	if s < 90 {
		t.Errorf("perfect traveler = %.1f, want >= 90", s)
	}
	// Bad traveler
	s = ComputeTravelerScore(0.3, 0.2, 2.0, 0.5)
	if s > 40 {
		t.Errorf("bad traveler = %.1f, want <= 40", s)
	}
}

func TestApplyTrustScoreToMatching(t *testing.T) {
	// High trust = boost
	highTrust := TrustScore{OverallScore: 80}
	adjusted := ApplyTrustScoreToMatching(0.5, highTrust)
	if adjusted <= 0.5 {
		t.Errorf("high trust should boost score, got %.3f", adjusted)
	}
	// Low trust = penalty
	lowTrust := TrustScore{OverallScore: 10}
	adjusted = ApplyTrustScoreToMatching(0.5, lowTrust)
	if adjusted >= 0.5 {
		t.Errorf("low trust should reduce score, got %.3f", adjusted)
	}
}

func TestIsTrustApprovedForDeal(t *testing.T) {
	good := TrustScore{OverallScore: 60, DisputeRate: 0.05}
	if !IsTrustApprovedForDeal(good) {
		t.Error("good trust should be approved")
	}
	badScore := TrustScore{OverallScore: 20, DisputeRate: 0.05}
	if IsTrustApprovedForDeal(badScore) {
		t.Error("low overall score should be rejected")
	}
	badDispute := TrustScore{OverallScore: 60, DisputeRate: 0.3}
	if IsTrustApprovedForDeal(badDispute) {
		t.Error("high dispute rate should be rejected")
	}
}

// ── 11. DEAL CLOSER HARDENING TESTS ────────────────────────────────────────────

func TestStaleOfferThreshold(t *testing.T) {
	if StaleOfferThreshold != 10*time.Minute {
		t.Errorf("stale threshold = %v, want 10m", StaleOfferThreshold)
	}
}

func TestCancelWindowMinutes(t *testing.T) {
	if CancelWindowMinutes != 2 {
		t.Errorf("cancel window = %d, want 2", CancelWindowMinutes)
	}
}

func TestAutoAcceptSettingsDefaults(t *testing.T) {
	s := AutoAcceptSettings{}
	if s.AutoAcceptEnabled {
		t.Error("auto-accept should default to false")
	}
	if s.MaxAutoAcceptAmountCents != 0 {
		t.Error("max amount should default to 0 (no limit)")
	}
}
