package resources

import (
	"context"
	"log/slog"

	"github.com/geocore-next/backend/pkg/telemetry"
)

// Proposal is an optimization proposal generated by the Cloud OS.
type Proposal struct {
	Resource     string  `json:"resource"` // api, wallet, fraud, kafka
	Action       string  `json:"action"`   // scale_up, scale_down, failover, adjust_threshold
	Target       string  `json:"target"`
	RiskScore    float64 `json:"risk_score"`    // 0-1
	ExpectedGain float64 `json:"expected_gain"` // % improvement
	Reason       string  `json:"reason"`
}

// ClusterState is the current state of all managed resources.
type ClusterState struct {
	API    APIResource    `json:"api"`
	Wallet WalletResource `json:"wallet"`
	Fraud  FraudResource  `json:"fraud"`
	Kafka  KafkaResource  `json:"kafka"`
}

// DesiredState is the desired state read from Git.
type DesiredState struct {
	APIVersion    string `json:"api_version"`
	FraudSensitivity string `json:"fraud_sensitivity"`
	MinReplicas   int    `json:"min_replicas"`
	MaxReplicas   int    `json:"max_replicas"`
}

// Change represents a detected Git change (from gitops package).
type Change struct {
	Service string
	Version string
	Env     string
}

// Manager manages all Cloud OS resources as a unified system.
type Manager struct {
	state   ClusterState
	desired DesiredState
}

// NewManager creates a resource manager with default state.
func NewManager() *Manager {
	return &Manager{
		state: ClusterState{
			API:    DefaultAPIResource(),
			Wallet: DefaultWalletResource(),
			Fraud:  DefaultFraudResource(),
			Kafka:  DefaultKafkaResource(),
		},
		desired: DesiredState{
			MinReplicas:   2,
			MaxReplicas:   10,
			FraudSensitivity: "medium",
		},
	}
}

// CollectState gathers the current state of all resources.
func (m *Manager) CollectState(ctx context.Context, metrics telemetry.MetricsSnapshot) ClusterState {
	m.state.API.CPUUtilization = metrics.CPUUsage
	m.state.API.RPS = metrics.RPS
	m.state.Kafka.ConsumerLag = metrics.KafkaLag
	m.state.Wallet.ErrorRate = metrics.ErrorRate
	return m.state
}

// DesiredFromChanges converts Git changes into desired state.
func (m *Manager) DesiredFromChanges(changes []Change) DesiredState {
	for _, c := range changes {
		if c.Service == "api" {
			m.desired.APIVersion = c.Version
		}
	}
	return m.desired
}

// Diff computes proposals to converge current state toward desired state.
func (m *Manager) Diff(state ClusterState, desired DesiredState) []Proposal {
	var proposals []Proposal

	// API scaling
	if state.API.NeedsScaleUp() {
		proposals = append(proposals, Proposal{
			Resource:     "api",
			Action:       "scale_up",
			Target:       "api-deployment",
			RiskScore:    0.1,
			ExpectedGain: 30,
			Reason:       "CPU > 70% or high RPS per pod",
		})
	}
	if state.API.NeedsScaleDown() {
		proposals = append(proposals, Proposal{
			Resource:     "api",
			Action:       "scale_down",
			Target:       "api-deployment",
			RiskScore:    0.2,
			ExpectedGain: 20,
			Reason:       "CPU < 30% with low RPS — overprovisioned",
		})
	}

	// Wallet safety
	if state.Wallet.CriticalAlert() {
		proposals = append(proposals, Proposal{
			Resource:     "wallet",
			Action:       "emergency_audit",
			Target:       "wallet-service",
			RiskScore:    0.05,
			ExpectedGain: 100,
			Reason:       "BALANCE INVARIANT VIOLATED — critical alert",
		})
	}

	// Fraud sensitivity
	if state.Fraud.NeedsSensitivityIncrease() {
		proposals = append(proposals, Proposal{
			Resource:     "fraud",
			Action:       "increase_sensitivity",
			Target:       "fraud-engine",
			RiskScore:    0.15,
			ExpectedGain: 50,
			Reason:       "Fraud rate spike detected",
		})
	}
	if state.Fraud.NeedsSensitivityDecrease() {
		proposals = append(proposals, Proposal{
			Resource:     "fraud",
			Action:       "decrease_sensitivity",
			Target:       "fraud-engine",
			RiskScore:    0.1,
			ExpectedGain: 30,
			Reason:       "False positive rate too high",
		})
	}

	// Kafka lag
	if state.Kafka.NeedsScaleUp() {
		proposals = append(proposals, Proposal{
			Resource:     "kafka",
			Action:       "scale_consumers",
			Target:       "kafka-consumers",
			RiskScore:    0.3,
			ExpectedGain: 60,
			Reason:       "Consumer lag exceeds threshold",
		})
	}

	if len(proposals) > 0 {
		slog.Info("cloudos: proposals generated", "count", len(proposals))
	}

	return proposals
}

// State returns the current cluster state.
func (m *Manager) State() ClusterState {
	return m.state
}
